### PR TITLE
Added support for parsing the origin in the Path.

### PR DESCRIPTION
**Pull request by phani2410**
Checked for ':' in path attribute

### CODE REVIEW

**Comment by phani2410** [comment]
Please check travis CI logs. I am unable to figure out. if the issue is due to the code.

**Comment by samribeiro** [comment]
@boleifu can you check if this works for you?

**Comment by samribeiro** [comment]
thanks @phani2410 
@boleifu has updated the go version for the tests, that was likely the cause they were breaking.
I have requested @boleifu to check that this change does not impact his projects.

**Comment by samribeiro** [comment]
may be causing #43

**Pull request merged**
