### PR TITLE
Feature: Add support for python virtualenv

### PR DESCRIPTION
**Pull request by markuscraig**
* Adds a python virtualenv 'requirements.txt' file for dependencies
* Updates the README with virtualenv how-to's
* Adds .gitignore for python files

### CODE REVIEW

**Comment by tejaskumark** [comment]
@markuscraig I am facing while running py_gnmicli.py from python virtual env is as below, can you please guide me how to fix this in virtual env. While same is working on system python setup.
Traceback (most recent call last):
  File "py_gnmicli.py", line 44, in <module>
    import gnmi_pb2
  File "/home/tejaskumar/go/src/github.com/google/gnxi/gnmi_cli_py/gnmi_pb2.py", line 29, in <module>
    dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,gnmi__ext__pb2.DESCRIPTOR,])
  File "/home/tejaskumar/env/project_env/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "gnmi.proto":
  gnmi.proto: Import "gnmi_ext.proto" has not been loaded.
  gnmi.SubscribeRequest.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.
  gnmi.SubscribeResponse.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.
  gnmi.SetRequest.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.
  gnmi.SetResponse.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.
  gnmi.GetRequest.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.
  gnmi.GetResponse.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.
  gnmi.CapabilityRequest.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.
  gnmi.CapabilityResponse.extension: "gnmi_ext.Extension" seems to be defined in "proto/gnmi_ext/gnmi_ext.proto", which is not imported by "gnmi.proto".  To use it here, please add the necessary import.

**Comment by markuscraig** [comment]
@tejaskumark I had the same problem and committed this fix to `dependencies.txt` (which adds the '--no-binary' option to the 'protobuf' entry)...
```
protobuf==3.6.1 --no-binary=protobuf
```

Do you see that update in your `requirements.txt` file?

Also, make sure that you delete your virtualenv and try again...
```
$ rm -Rf venv
$ virtualenv venv
$ . venv/bin/activate
$ pip install -r requirements.txt
```

**Comment by mike-albano** [comment]
@tejaskumark , does @markuscraig fix work for you? If yes, I think we can merge/close this.

**Comment by tejaskumark** [comment]
@mike-albano Yes this fix worked. We can merge and close this issue.
@markuscraig Sorry, I could not reply earlier. Very much appreciate your fast response.

**Pull request merged**
